USE yecdata;

-- Insert test admin data
INSERT INTO Administrator VALUES (NULL, 'admin001', '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'admin001@gmail.com', 0);

-- Insert test school data
INSERT INTO School VALUES(NULL,'British Columbia Institute of Technology','Canada','British Columbia','Burnaby');
INSERT INTO School VALUES(NULL,'Burnaby Test school 01','Canada','British Columbia','Burnaby');
INSERT INTO School VALUES(NULL,'Burnaby Test school 02','Canada','British Columbia','Burnaby');
INSERT INTO School VALUES(NULL,'Burnaby Test school 03','Canada','British Columbia','Burnaby');
INSERT INTO School VALUES(NULL,'Burnaby Test school 04','Canada','British Columbia','Burnaby');
INSERT INTO School VALUES(NULL,'Burnaby Test school 05','Canada','British Columbia','Burnaby');
INSERT INTO School VALUES(NULL,'Burnaby Test school 06','Canada','British Columbia','Burnaby');
INSERT INTO School VALUES(NULL,'Burnaby Test school 07','Canada','British Columbia','Burnaby');
INSERT INTO School VALUES(NULL,'Burnaby Test school 08','Canada','British Columbia','Burnaby');
INSERT INTO School VALUES(NULL,'Burnaby Test school 09','Canada','British Columbia','Burnaby');
INSERT INTO School VALUES(NULL,'Burnaby Test school 10','Canada','British Columbia','Burnaby');
INSERT INTO School VALUES(NULL,'Vancouver Test school 01','Canada','British Columbia','Vancouver');
INSERT INTO School VALUES(NULL,'Vancouver Test school 02','Canada','British Columbia','Vancouver');
INSERT INTO School VALUES(NULL,'Vancouver Test school 03','Canada','British Columbia','Vancouver');
INSERT INTO School VALUES(NULL,'Vancouver Test school 04','Canada','British Columbia','Vancouver');
INSERT INTO School VALUES(NULL,'Vancouver Test school 05','Canada','British Columbia','Vancouver');
INSERT INTO School VALUES(NULL,'Vancouver Test school 06','Canada','British Columbia','Vancouver');
INSERT INTO School VALUES(NULL,'Vancouver Test school 07','Canada','British Columbia','Vancouver');
INSERT INTO School VALUES(NULL,'Vancouver Test school 08','Canada','British Columbia','Vancouver');
INSERT INTO School VALUES(NULL,'Vancouver Test school 09','Canada','British Columbia','Vancouver');
INSERT INTO School VALUES(NULL,'Vancouver Test school 10','Canada','British Columbia','Vancouver');
INSERT INTO School VALUES(NULL,'Richmond Test school 01','Canada','British Columbia','Richmond');
INSERT INTO School VALUES(NULL,'Richmond Test school 02','Canada','British Columbia','Richmond');
INSERT INTO School VALUES(NULL,'Richmond Test school 03','Canada','British Columbia','Richmond');
INSERT INTO School VALUES(NULL,'Richmond Test school 04','Canada','British Columbia','Richmond');
INSERT INTO School VALUES(NULL,'Richmond Test school 05','Canada','British Columbia','Richmond');
INSERT INTO School VALUES(NULL,'Richmond Test school 06','Canada','British Columbia','Richmond');
INSERT INTO School VALUES(NULL,'Richmond Test school 07','Canada','British Columbia','Richmond');
INSERT INTO School VALUES(NULL,'Richmond Test school 08','Canada','British Columbia','Richmond');
INSERT INTO School VALUES(NULL,'Richmond Test school 09','Canada','British Columbia','Richmond');
INSERT INTO School VALUES(NULL,'Richmond Test school 10','Canada','British Columbia','Richmond');
INSERT INTO School VALUES(NULL,'Surrey Test school 01','Canada','British Columbia','Surrey');
INSERT INTO School VALUES(NULL,'Surrey Test school 02','Canada','British Columbia','Surrey');
INSERT INTO School VALUES(NULL,'Surrey Test school 03','Canada','British Columbia','Surrey');
INSERT INTO School VALUES(NULL,'Surrey Test school 04','Canada','British Columbia','Surrey');
INSERT INTO School VALUES(NULL,'Surrey Test school 05','Canada','British Columbia','Surrey');
INSERT INTO School VALUES(NULL,'Surrey Test school 06','Canada','British Columbia','Surrey');
INSERT INTO School VALUES(NULL,'Surrey Test school 07','Canada','British Columbia','Surrey');
INSERT INTO School VALUES(NULL,'Surrey Test school 08','Canada','British Columbia','Surrey');
INSERT INTO School VALUES(NULL,'Surrey Test school 09','Canada','British Columbia','Surrey');
INSERT INTO School VALUES(NULL,'Surrey Test school 10','Canada','British Columbia','Surrey');
INSERT INTO School VALUES(NULL,'Coquitlam Test school 01','Canada','British Columbia','Coquitlam');
INSERT INTO School VALUES(NULL,'Coquitlam Test school 02','Canada','British Columbia','Coquitlam');
INSERT INTO School VALUES(NULL,'Coquitlam Test school 03','Canada','British Columbia','Coquitlam');
INSERT INTO School VALUES(NULL,'Coquitlam Test school 04','Canada','British Columbia','Coquitlam');
INSERT INTO School VALUES(NULL,'Coquitlam Test school 05','Canada','British Columbia','Coquitlam');
INSERT INTO School VALUES(NULL,'Coquitlam Test school 06','Canada','British Columbia','Coquitlam');
INSERT INTO School VALUES(NULL,'Coquitlam Test school 07','Canada','British Columbia','Coquitlam');
INSERT INTO School VALUES(NULL,'Coquitlam Test school 08','Canada','British Columbia','Coquitlam');
INSERT INTO School VALUES(NULL,'Coquitlam Test school 09','Canada','British Columbia','Coquitlam');
INSERT INTO School VALUES(NULL,'Coquitlam Test school 10','Canada','British Columbia','Coquitlam');

-- Insert test student data
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'liang', 'zhao', 'vic', 0 ,1, 'zhaoliangbz@gmail.com',0);

INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test01', 0 ,1, 'test01@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test02', 0 ,1, 'test02@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test03', 0 ,1, 'test03@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test04', 0 ,1, 'test04@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test05', 0 ,1, 'test05@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test06', 0 ,1, 'test06@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test07', 0 ,1, 'test07@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test08', 0 ,1, 'test08@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test09', 0 ,1, 'test09@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test10', 0 ,1, 'test10@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test11', 0 ,1, 'test11@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test12', 0 ,1, 'test12@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test13', 0 ,1, 'test13@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test14', 0 ,1, 'test14@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test15', 0 ,1, 'test15@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test16', 0 ,1, 'test16@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test17', 0 ,1, 'test17@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test18', 0 ,1, 'test18@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test19', 0 ,1, 'test19@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test20', 0 ,1, 'test20@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test21', 0 ,FLOOR(RAND() * 20 + 1), 'test21@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test22', 0 ,FLOOR(RAND() * 20 + 1), 'test22@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test23', 0 ,FLOOR(RAND() * 20 + 1), 'test23@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test24', 0 ,FLOOR(RAND() * 20 + 1), 'test24@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test25', 0 ,FLOOR(RAND() * 20 + 1), 'test25@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test26', 0 ,FLOOR(RAND() * 20 + 1), 'test26@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test27', 0 ,FLOOR(RAND() * 20 + 1), 'test27@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test28', 0 ,FLOOR(RAND() * 20 + 1), 'test28@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test29', 0 ,FLOOR(RAND() * 20 + 1), 'test29@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test30', 0 ,FLOOR(RAND() * 20 + 1), 'test30@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test31', 0 ,FLOOR(RAND() * 20 + 1), 'test31@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test32', 0 ,FLOOR(RAND() * 20 + 1), 'test32@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test33', 0 ,FLOOR(RAND() * 20 + 1), 'test33@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test34', 0 ,FLOOR(RAND() * 20 + 1), 'test34@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test35', 0 ,FLOOR(RAND() * 20 + 1), 'test35@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test36', 0 ,FLOOR(RAND() * 20 + 1), 'test36@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test37', 0 ,FLOOR(RAND() * 20 + 1), 'test37@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test38', 0 ,FLOOR(RAND() * 20 + 1), 'test38@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test39', 0 ,FLOOR(RAND() * 20 + 1), 'test39@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test40', 0 ,FLOOR(RAND() * 20 + 1), 'test40@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test41', 0 ,FLOOR(RAND() * 20 + 1), 'test41@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test42', 0 ,FLOOR(RAND() * 20 + 1), 'test42@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test43', 0 ,FLOOR(RAND() * 20 + 1), 'test43@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test44', 0 ,FLOOR(RAND() * 20 + 1), 'test44@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test45', 0 ,FLOOR(RAND() * 20 + 1), 'test45@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test46', 0 ,FLOOR(RAND() * 20 + 1), 'test46@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test47', 0 ,FLOOR(RAND() * 20 + 1), 'test47@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test48', 0 ,FLOOR(RAND() * 20 + 1), 'test48@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test49', 0 ,FLOOR(RAND() * 20 + 1), 'test49@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test50', 0 ,FLOOR(RAND() * 20 + 1), 'test50@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test51', 0 ,FLOOR(RAND() * 20 + 1), 'test51@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test52', 0 ,FLOOR(RAND() * 20 + 1), 'test52@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test53', 0 ,FLOOR(RAND() * 20 + 1), 'test53@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test54', 0 ,FLOOR(RAND() * 20 + 1), 'test54@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test55', 0 ,FLOOR(RAND() * 20 + 1), 'test55@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test56', 0 ,FLOOR(RAND() * 20 + 1), 'test56@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test57', 0 ,FLOOR(RAND() * 20 + 1), 'test57@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test58', 0 ,FLOOR(RAND() * 20 + 1), 'test58@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test59', 0 ,FLOOR(RAND() * 20 + 1), 'test59@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test60', 0 ,FLOOR(RAND() * 20 + 1), 'test60@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test61', 0 ,FLOOR(RAND() * 20 + 1), 'test61@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test62', 0 ,FLOOR(RAND() * 20 + 1), 'test62@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test63', 0 ,FLOOR(RAND() * 20 + 1), 'test63@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test64', 0 ,FLOOR(RAND() * 20 + 1), 'test64@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test65', 0 ,FLOOR(RAND() * 20 + 1), 'test65@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test66', 0 ,FLOOR(RAND() * 20 + 1), 'test66@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test67', 0 ,FLOOR(RAND() * 20 + 1), 'test67@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test68', 0 ,FLOOR(RAND() * 20 + 1), 'test68@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test69', 0 ,FLOOR(RAND() * 20 + 1), 'test69@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test70', 0 ,FLOOR(RAND() * 20 + 1), 'test70@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test71', 0 ,FLOOR(RAND() * 20 + 1), 'test71@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test72', 0 ,FLOOR(RAND() * 20 + 1), 'test72@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test73', 0 ,FLOOR(RAND() * 20 + 1), 'test73@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test74', 0 ,FLOOR(RAND() * 20 + 1), 'test74@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test75', 0 ,FLOOR(RAND() * 20 + 1), 'test75@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test76', 0 ,FLOOR(RAND() * 20 + 1), 'test76@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test77', 0 ,FLOOR(RAND() * 20 + 1), 'test77@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test78', 0 ,FLOOR(RAND() * 20 + 1), 'test78@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test79', 0 ,FLOOR(RAND() * 20 + 1), 'test79@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test80', 0 ,FLOOR(RAND() * 20 + 1), 'test80@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test81', 0 ,FLOOR(RAND() * 20 + 1), 'test81@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test82', 0 ,FLOOR(RAND() * 20 + 1), 'test82@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test83', 0 ,FLOOR(RAND() * 20 + 1), 'test83@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test84', 0 ,FLOOR(RAND() * 20 + 1), 'test84@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test85', 0 ,FLOOR(RAND() * 20 + 1), 'test85@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test86', 0 ,FLOOR(RAND() * 20 + 1), 'test86@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test87', 0 ,FLOOR(RAND() * 20 + 1), 'test87@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test88', 0 ,FLOOR(RAND() * 20 + 1), 'test88@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test89', 0 ,FLOOR(RAND() * 20 + 1), 'test89@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test90', 0 ,FLOOR(RAND() * 20 + 1), 'test90@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test91', 0 ,FLOOR(RAND() * 20 + 1), 'test91@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test92', 0 ,FLOOR(RAND() * 20 + 1), 'test92@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test93', 0 ,FLOOR(RAND() * 20 + 1), 'test93@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test94', 0 ,FLOOR(RAND() * 20 + 1), 'test94@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test95', 0 ,FLOOR(RAND() * 20 + 1), 'test95@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test96', 0 ,FLOOR(RAND() * 20 + 1), 'test96@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test97', 0 ,FLOOR(RAND() * 20 + 1), 'test97@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test98', 0 ,FLOOR(RAND() * 20 + 1), 'test98@gmail.com',0);
INSERT INTO User VALUES (NULL, '$2y$12$ZdrjTKpRo0UnQ6wyYBYZmOo5dW5ZZQZJTTfd4M9ulvyWt57J3fLMi', 'first', 'last', 'test99', 0 ,FLOOR(RAND() * 20 + 1), 'test99@gmail.com',0);

-- Insert some user action data
INSERT INTO UserAction VALUES (1,1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO UserAction VALUES (1,2, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO UserAction VALUES (1,3, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO UserAction VALUES (1,4, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO UserAction VALUES (1,5, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO UserAction VALUES (1,6, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO UserAction VALUES (3,6, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO UserAction VALUES (3,1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO UserAction VALUES (3,7, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);

-- Insert some user accomplishment data for testing the scores and ranking
INSERT INTO Accomplishment VALUES(2 , FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(3 , FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(4 , FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(5 , FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(6 , FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(7 , FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(8 , FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(9 , FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(10, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(11, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(12, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(13, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(14, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(15, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(16, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(17, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(18, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(19, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(20, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(21, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(22, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(23, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(24, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(25, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(26, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(27, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(28, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(29, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(30, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(31, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(32, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(33, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(34, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(35, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(36, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(37, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(38, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(39, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
INSERT INTO Accomplishment VALUES(40, FLOOR(RAND() * 18) + 1, CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 365) DAY + INTERVAL FLOOR(RAND() * 30000) SECOND);
