#!/bin/bash
echo "Enter password for yecuser:"
read -s db_password
#echo $db_password

mysql -u "yecuser" --password="$db_password" --show-warnings=true
mysql -u "yecuser" --password="$db_password" --show-warnings=true
mysql -u "yecuser" --password="$db_password" --show-warnings=true
