#!/bin/bash
echo "Enter password for yecuser:"
read -s db_password
#echo $db_password

mysql -u "yecuser" --password="$db_password" --show-warnings=false < drop_database.sql >/dev/null
mysql -u "yecuser" --password="$db_password" --show-warnings=false < setup_db.sql 2>/dev/null
mysql -u "yecuser" --password="$db_password" --show-warnings=false < insert_testdata.sql 2>/dev/null
